# Project: Array Test Program
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = "Array\ Test\ Program.o" $(RES)
LINKOBJ  = "Array Test Program.o" $(RES)
LIBS =  -L"D:/Dev-Cpp/lib"  
INCS =  -I"D:/Dev-Cpp/include" 
CXXINCS =  -I"D:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/Dev-Cpp/include/c++/3.4.2/backward"  -I"D:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"D:/Dev-Cpp/include/c++/3.4.2"  -I"D:/Dev-Cpp/include" 
BIN  = "Array Test Program.exe"
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before "Array Test Program.exe" all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Array Test Program.exe" $(LIBS)

"Array\ Test\ Program.o": Array\ Test\ Program.cpp
	$(CPP) -c "Array Test Program.cpp" -o "Array Test Program.o" $(CXXFLAGS)
